[tool.poetry]
name = "idao-challenge"
version = "0.1.0"
description = "International Data Analysis Olympiad"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.10"
pandas = "^1.3.1"
numpy = "^1.21.1"
scipy = "^1.7.1"
jupyter = "^1.0.0"
ipykernel = "^6.1.0"
plotly = "^5.2.1"
matplotlib = "^3.4.3"
tqdm = "^4.62.0"
scikit-learn = "^1.0.2"
pymatgen = "^2022.2.1"
ase = "^3.22.1"
nglview = "^3.0.3"
jarvis-tools = "^2022.1.10"
networkx = "^2.7.1"
black = "^22.1.0"
flake8 = "^4.0.1"
mypy = "^0.941"
isort = "^5.10.1"
pre-commit = "^2.17.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 119
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
