data:
  private:
    root: data/dichalcogenides_private
    defects: data/dichalcogenides_private/defects
  public:
    root: data/dichalcogenides_public
    defects: data/dichalcogenides_public/defects/structure
model:
  weights: 'weights/val_mae_00750_0.010320.hdf5'
